# nonk8s
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
spec:
  destination:
    namespace: kuberstar
    server: 'https://kubernetes.default.svc'
  source:
    path: app
    repoURL: 'https://github.com/m-minasyan/helm-local.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true