# nonk8s
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: promtail
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.2.2
    helm:
      values: |
        config:
          lokiAddress: http://loki-gateway.monitoring/loki/api/v1/push   # FQDN of loki-gateway's push endpoint
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true