apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-registry
spec:
  destination:
    namespace: docker-registry
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://helm.twun.io'
    targetRevision: 2.1.0
    chart: docker-registry
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true